apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`vm.cuiliangblog.cn`) # 域名
    kind: Rule
    services:
      - name: vmselect-vmcluster   # 与svc的name一致
        port: 8481    # 与svc的port一致