apiVersion: v1
kind: Secret
metadata:
  name: thanosruler-alertmanager-config
  namespace: monitoring
stringData:
  alertmanager-configs.yaml: |-
    alertmanagers:
    - static_configs: ["alertmanager-main:9093"]
      scheme: http
      timeout: 30s
      api_version: v1   
type: Opaque